name: Workflow Events
on: 
# push:
#  branches:
#   - main
 pull_request:
  branches:
   - main
jobs: 
 workflow_events:
  runs-on: ubuntu-latest
   steps: 
    - name: echo event name
      run: echo "The event name is ${{ github.event_name }}"  
