name: Workflow Events
on: 
  pull_request:
   branches:
    - main
jobs: 
 workflow_events:
  runs-on: ubuntu-latest
  steps: 
    - name: echo event name
      run: | 
       echo "The event name is ${{ github.event_name }}" 
       echo "The event action is ${{ github.event.action }}"
       echo "The PR number is ${{ github.event.number }}"
       echo "The commit message is ${{ github.event.head_commit.message }}"